services:
  app:
    build:
      context: .
      target: dev
    volumes:
      - ./:/app/:Z
    environment:
      JWT_SECRET: secret 
    ports:
      - 8080:8080

  mongo-express:
    image: docker.io/library/mongo-express
    restart: always
    links:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
